# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 603)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(50, 0, 400, 541))
        self.verticalWidget.setMinimumSize(QtCore.QSize(400, 541))
        self.verticalWidget.setMaximumSize(QtCore.QSize(771, 541))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLabel = QtWidgets.QLabel(self.verticalWidget)
        self.mainLabel.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout.addWidget(self.mainLabel)
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonOne = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOne.sizePolicy().hasHeightForWidth())
        self.buttonOne.setSizePolicy(sizePolicy)
        self.buttonOne.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonOne.setFont(font)
        self.buttonOne.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonOne.setObjectName("buttonOne")
        self.gridLayout.addWidget(self.buttonOne, 0, 0, 1, 1)
        self.buttonZero = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonZero.sizePolicy().hasHeightForWidth())
        self.buttonZero.setSizePolicy(sizePolicy)
        self.buttonZero.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonZero.setFont(font)
        self.buttonZero.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonZero.setObjectName("buttonZero")
        self.gridLayout.addWidget(self.buttonZero, 3, 1, 1, 1)
        self.buttonFive = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFive.sizePolicy().hasHeightForWidth())
        self.buttonFive.setSizePolicy(sizePolicy)
        self.buttonFive.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonFive.setFont(font)
        self.buttonFive.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonFive.setObjectName("buttonFive")
        self.gridLayout.addWidget(self.buttonFive, 1, 1, 1, 1)
        self.buttonSix = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSix.sizePolicy().hasHeightForWidth())
        self.buttonSix.setSizePolicy(sizePolicy)
        self.buttonSix.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonSix.setFont(font)
        self.buttonSix.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonSix.setObjectName("buttonSix")
        self.gridLayout.addWidget(self.buttonSix, 1, 2, 1, 1)
        self.buttonSlash = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSlash.sizePolicy().hasHeightForWidth())
        self.buttonSlash.setSizePolicy(sizePolicy)
        self.buttonSlash.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonSlash.setFont(font)
        self.buttonSlash.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonSlash.setObjectName("buttonSlash")
        self.gridLayout.addWidget(self.buttonSlash, 3, 2, 1, 1)
        self.buttonC = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonC.sizePolicy().hasHeightForWidth())
        self.buttonC.setSizePolicy(sizePolicy)
        self.buttonC.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonC.setFont(font)
        self.buttonC.setStyleSheet("background-color: rgb(230, 126, 34);")
        self.buttonC.setObjectName("buttonC")
        self.gridLayout.addWidget(self.buttonC, 0, 3, 1, 1)
        self.buttonSeven = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSeven.sizePolicy().hasHeightForWidth())
        self.buttonSeven.setSizePolicy(sizePolicy)
        self.buttonSeven.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonSeven.setFont(font)
        self.buttonSeven.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonSeven.setObjectName("buttonSeven")
        self.gridLayout.addWidget(self.buttonSeven, 2, 0, 1, 1)
        self.buttonDiv = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDiv.sizePolicy().hasHeightForWidth())
        self.buttonDiv.setSizePolicy(sizePolicy)
        self.buttonDiv.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonDiv.setFont(font)
        self.buttonDiv.setStyleSheet("background-color: rgb(255, 190, 118);")
        self.buttonDiv.setObjectName("buttonDiv")
        self.gridLayout.addWidget(self.buttonDiv, 2, 3, 1, 1)
        self.buttonPlus = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlus.sizePolicy().hasHeightForWidth())
        self.buttonPlus.setSizePolicy(sizePolicy)
        self.buttonPlus.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonPlus.setFont(font)
        self.buttonPlus.setStyleSheet("background-color: rgb(255, 190, 118);")
        self.buttonPlus.setObjectName("buttonPlus")
        self.gridLayout.addWidget(self.buttonPlus, 3, 3, 1, 1)
        self.buttonTwo = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTwo.sizePolicy().hasHeightForWidth())
        self.buttonTwo.setSizePolicy(sizePolicy)
        self.buttonTwo.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonTwo.setFont(font)
        self.buttonTwo.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonTwo.setObjectName("buttonTwo")
        self.gridLayout.addWidget(self.buttonTwo, 0, 1, 1, 1)
        self.buttonNizh = QtWidgets.QPushButton(self.verticalWidget)
        self.buttonNizh.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonNizh.setFont(font)
        self.buttonNizh.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonNizh.setObjectName("buttonNizh")
        self.gridLayout.addWidget(self.buttonNizh, 3, 0, 1, 1)
        self.buttonClose = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClose.sizePolicy().hasHeightForWidth())
        self.buttonClose.setSizePolicy(sizePolicy)
        self.buttonClose.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonClose.setFont(font)
        self.buttonClose.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonClose.setObjectName("buttonClose")
        self.gridLayout.addWidget(self.buttonClose, 4, 2, 1, 1)
        self.buttonNine = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNine.sizePolicy().hasHeightForWidth())
        self.buttonNine.setSizePolicy(sizePolicy)
        self.buttonNine.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonNine.setFont(font)
        self.buttonNine.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonNine.setObjectName("buttonNine")
        self.gridLayout.addWidget(self.buttonNine, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.buttonThree = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonThree.sizePolicy().hasHeightForWidth())
        self.buttonThree.setSizePolicy(sizePolicy)
        self.buttonThree.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonThree.setFont(font)
        self.buttonThree.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonThree.setObjectName("buttonThree")
        self.gridLayout.addWidget(self.buttonThree, 0, 2, 1, 1)
        self.buttonFor = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFor.sizePolicy().hasHeightForWidth())
        self.buttonFor.setSizePolicy(sizePolicy)
        self.buttonFor.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonFor.setFont(font)
        self.buttonFor.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonFor.setObjectName("buttonFor")
        self.gridLayout.addWidget(self.buttonFor, 1, 0, 1, 1)
        self.buttonEq = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEq.sizePolicy().hasHeightForWidth())
        self.buttonEq.setSizePolicy(sizePolicy)
        self.buttonEq.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonEq.setFont(font)
        self.buttonEq.setStyleSheet("background-color: rgb(230, 126, 34);")
        self.buttonEq.setObjectName("buttonEq")
        self.gridLayout.addWidget(self.buttonEq, 5, 3, 1, 1)
        self.buttonEight = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEight.sizePolicy().hasHeightForWidth())
        self.buttonEight.setSizePolicy(sizePolicy)
        self.buttonEight.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonEight.setFont(font)
        self.buttonEight.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonEight.setObjectName("buttonEight")
        self.gridLayout.addWidget(self.buttonEight, 2, 1, 1, 1)
        self.buttonMinus = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMinus.sizePolicy().hasHeightForWidth())
        self.buttonMinus.setSizePolicy(sizePolicy)
        self.buttonMinus.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonMinus.setFont(font)
        self.buttonMinus.setStyleSheet("background-color: rgb(255, 190, 118);")
        self.buttonMinus.setObjectName("buttonMinus")
        self.gridLayout.addWidget(self.buttonMinus, 4, 3, 1, 1)
        self.buttonMul = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMul.sizePolicy().hasHeightForWidth())
        self.buttonMul.setSizePolicy(sizePolicy)
        self.buttonMul.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonMul.setFont(font)
        self.buttonMul.setStyleSheet("background-color: rgb(255, 190, 118);")
        self.buttonMul.setObjectName("buttonMul")
        self.gridLayout.addWidget(self.buttonMul, 1, 3, 1, 1)
        self.buttonHelper = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonHelper.sizePolicy().hasHeightForWidth())
        self.buttonHelper.setSizePolicy(sizePolicy)
        self.buttonHelper.setMinimumSize(QtCore.QSize(60, 60))
        self.buttonHelper.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonHelper.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonHelper.setObjectName("buttonHelper")
        self.gridLayout.addWidget(self.buttonHelper, 4, 1, 1, 1)
        self.buttonOpen = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOpen.sizePolicy().hasHeightForWidth())
        self.buttonOpen.setSizePolicy(sizePolicy)
        self.buttonOpen.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonOpen.setFont(font)
        self.buttonOpen.setStyleSheet("background-color: rgb(116, 185, 255);")
        self.buttonOpen.setObjectName("buttonOpen")
        self.gridLayout.addWidget(self.buttonOpen, 4, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setRowStretch(0, 10)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Правило замены: 1½ = 1_1/2"))
        self.buttonOne.setText(_translate("MainWindow", "1"))
        self.buttonZero.setText(_translate("MainWindow", "0"))
        self.buttonFive.setText(_translate("MainWindow", "5"))
        self.buttonSix.setText(_translate("MainWindow", "6"))
        self.buttonSlash.setText(_translate("MainWindow", "/"))
        self.buttonC.setText(_translate("MainWindow", "C"))
        self.buttonSeven.setText(_translate("MainWindow", "7"))
        self.buttonDiv.setText(_translate("MainWindow", "÷"))
        self.buttonPlus.setText(_translate("MainWindow", "+"))
        self.buttonTwo.setText(_translate("MainWindow", "2"))
        self.buttonNizh.setText(_translate("MainWindow", "_"))
        self.buttonClose.setText(_translate("MainWindow", ")"))
        self.buttonNine.setText(_translate("MainWindow", "9"))
        self.buttonThree.setText(_translate("MainWindow", "3"))
        self.buttonFor.setText(_translate("MainWindow", "4"))
        self.buttonEq.setText(_translate("MainWindow", "="))
        self.buttonEight.setText(_translate("MainWindow", "8"))
        self.buttonMinus.setText(_translate("MainWindow", "-"))
        self.buttonMul.setText(_translate("MainWindow", "*"))
        self.buttonHelper.setText(_translate("MainWindow", "Обучающий\n"
"режим"))
        self.buttonOpen.setText(_translate("MainWindow", "("))
